name: Down

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
